# -*- coding: utf-8 -*-
"""Customer_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6bO_-unhoZAstOPF5OY5UJG_lBkFbcY
"""

!pip install transformers datasets

from transformers import pipeline
from datasets import load_dataset

dataset = load_dataset("amazon_polarity")

# Load a pre-trained sentiment model (DistilBERT)
sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")


sample_reviews = [
    dataset["train"][0]["content"],
    dataset["train"][1]["content"],
    "The product quality is very bad.",
    "I love this product, totally worth the money!"
]

results = sentiment_pipeline(sample_reviews)

# Print results
for review, result in zip(sample_reviews, results):
    print(f"Review: {review}\nPrediction: {result['label']} (confidence: {result['score']:.2f})\n")

!pip install torch

import matplotlib.pyplot as plt

# Count positive and negative results
positive_count = sum(1 for result in results if result['label'] == 'POSITIVE')
negative_count = sum(1 for result in results if result['label'] == 'NEGATIVE')

# Sentiment distribution
labels = ["Positive", "Negative"]
counts = [positive_count, negative_count]

plt.bar(labels, counts, color=["green", "red"])
plt.title("Amazon Reviews Sentiment Distribution (100 samples)")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()

